name: Desplegar Backend Java

on:
  push:
    branches: [ main ]
    paths: [ 'Backend/Java/**' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Confirmado en tu pom.xml
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd Backend/Java
          mvn clean package -DskipTests
          # Agrega esta línea para renombrar el JAR generado a app.jar
          mv target/*.jar target/app.jar

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'api-java-aves2'
          publish-profile: ${{ secrets.AZURE_JAVA_PUBLISH_PROFILE }}
          package: 'Backend/Java/target/app.jar' # Aquí cambiaste *.jar por app.jar
